// lib/src/colors.dart
import 'package:flutter/material.dart';

// This file will be generated by the Figma parser
// Placeholder implementation until generated
class AppColors {
  static const Color placeholder = Color(0xFF000000);

  AppColors._();
}

class AppThemeColors extends ThemeExtension<AppThemeColors> {
  final Color text;

  const AppThemeColors({
    required this.text,
  });

  static AppThemeColors get light => const AppThemeColors(
    text: Color(0xFF000000),
  );

  static AppThemeColors get dark => const AppThemeColors(
    text: Color(0xFFFFFFFF),
  );

  @override
  ThemeExtension<AppThemeColors> copyWith({Color? text}) {
    return AppThemeColors(
      text: text ?? this.text,
    );
  }

  @override
  ThemeExtension<AppThemeColors> lerp(
    ThemeExtension<AppThemeColors>? other, double t) {
    if (other is! AppThemeColors) {
      return this;
    }
    return AppThemeColors(
      text: Color.lerp(text, other.text, t)!,
    );
  }
}

extension BuildContextThemeExtension on BuildContext {
  AppThemeColors get colors => Theme.of(this).extension<AppThemeColors>()!;
}